env_name: Pendulum-v1
horizon: 10
dense: True
constants:
    - name: theta_thresh
      type: float
      value: 0.5
    - name: omega_thresh
      type: float
      value:  0.1
variables:
    - name: omega
      type: float
      location: obs
      identifier: 2
    - name: theta
      type: float
      location: info
      identifier: theta
specifications:
    - name: task
      descriptor: The pendulum will stabilize around upright for at least 10 steps.
      spec: task = eventually(always[0:10]((abs(theta) <= theta_thresh)))
      weight: 2.0