constants:
    - name: crash_thresh
      type: float
      value: 0.20943951023
    - name: rejoin_thresh
      type: float
      value: 0.0349066
variables:
    - name: x_val
      type: float
      location: obs
      identifier: 0
    - name: y_val
      type: float
      location: obs
      identifier: 1
    - name: z_val
      type: float
      location: obs
      identifier: 2
    - name: speed
      type: float
      location: info
      identifier: 3
specifications:
    - name: position_bound
      descriptor: cart remains in the bounds so that |pos| <= 2.4
      spec: position_bound = always(abs(pos) <= pos_max_thresh)
      weight: 1.0
    - name: angle_bound
      descriptor: cart keeps the pole upright in the bounds so that |angle| <= 12 degrees
      spec: angle_bound = always(abs(angle) <= angle_max_thresh)
      weight: 1.0
    - name: stability
      descriptor: The cart and pole stabilize so that the cart is within |pos| <= 0.5 and the pole is within |angle| <= 2 degrees
      spec: stability = eventually(always((abs(pos) <= angle_stability_thresh) and (abs(angle) <= pos_stability_thresh)))
      weight: 1.0