env_name: Pendulum-v1
constants:
    - name: theta_thresh
      type: float
      value: 0.1
    - name: omega_thresh
      type: float
      value:  0.01
variables:
    - name: omega
      type: float
      location: obs
      identifier: 2
    - name: theta
      type: float
      location: info
      identifier: theta
specifications:
    - name: task
      descriptor: The pendulum will stabilize around upright
      spec: task = eventually(always((abs(theta) <= theta_thresh) and (abs(omega) <= omega_thresh)))
      weight: 1.0