env_name: InvPendulum-v0
constants:
    - name: theta_thresh
      type: float
      value: 1.0
variables:
    - name: omega
      type: float
      location: obs
      identifier: 2
    - name: theta
      type: float
      location: info
      identifier: theta
specifications:
    - name: task
      descriptor: optional description
      spec: task = always((abs(theta) <= theta_thresh) and (abs(omega) <= 10.0))
      weight: 1.0