env_name: CartPole-v0
horizon: 1
host: 127.0.0.1
port: 8080
horizon: 1
constants:
    - name: angle_max_thresh
      type: float
      value: 0.0872665
    - name: pos_max_thresh
      type: float
      value: 0.5
variables:
    - name: pos
      type: float
      location: obs
      identifier: 0
    - name: angle
      type: float
      location: obs
      identifier: 2
reward:
      name: task
      true: 1
      currently_true: 2
      currently_false: -1
      false: -1